-- 코드를 입력하세요
SELECT ROUND(AVG(DAILY_FEE), 0) AS AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = 'SUV';

-- SELECT : 'SUV'인 자동차들의 평균 일일 대여 요금 + ROUND(숫자, 반올림할 자릿수) AS AVERGAGE_FEE
-- FROM CAR_RENTAL_COMPANY_CAR
-- WHERE : CAR_TYPE = 'SUV'