-- 코드를 입력하세요
SELECT FH.FLAVOR
FROM FIRST_HALF AS FH JOIN ICECREAM_INFO AS II ON FH.FLAVOR = II.FLAVOR
WHERE FH.TOTAL_ORDER >= 3000 AND II.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;

-- 총 주문량이 3,000 보다 높으면 
-- WHERE : FIRST_HALF의 TOTAL_ORDER >= 3000 AND INGREDIENT_TYPE : 'fruit_based'
-- SELECT : FLAVOR
-- ORDER BY : TOTAL_ORDER DESC;

